// TODO: global variables are bad
var names = {
  "firsts": [
    'Lars',
    'Fjörd',
    'Kröns',
    'Yasmin',
    'Dirk',
    'Bronson',
    'Testy',
    'Kurt',
    'Hans',
    'Earl',
    'Sloppy',
    'Jizzy',
    'Ivanna',
    'Ol\' Man',
    'Spanks',
    'Lusty',
    'Rusty',
    'Cissy',
    'Jinxy',
    'Jerome',
    'Pierre',
    'Harrison',
    'Pukey',
    'Red',
    'Buster',
    'Snipped',
    'Ingrid',
    'Julius',
    'Sherman',
    'Junior',
    'Yuri',
    'Johnson',
    'Ryder',
    'Gary',
    'Ulrich Von',
    'Dirty',
    'Chief',
    'Helga Von',
    'Dusty',
    'Smash',
    'Krusty',
    'Porky',
    'Itchy',
    'Count',
    'Countess',
    'Moist',
    'Matt',
    'Ben',
    'Jon',
    'Josh',
    'Kirkland\'s Best',
    'Shart',
    'Muffintop',
    'Areola',
    'Misty',
    'Cuppa Ma',
    'Master',
    'Fingershrew',
    'Dr.',
    'Dazzle',
    'Scoot',
    'Grandma',
    'Grandpa',
    'DJ',
    'Nordick',
    'Juicy',
    'Kitty',
    'Armando',
    'Dick',
    'Soupy',
    'Blowey',
    'Soapy',
    'Slaptit',
    'Tart',
    'Snuff',
    'Slurp',
    'Koalabutter',
    'Raggedy',
    'Pusty',
    'Pussycat',
    'Urethra',
    'Gondola',
    'Zucchini',
    'Sharty',
    'Toejam',
    'Santa',
    'Mother',
    'Penal',
    'Furry',
    'Woodtit',
    'Olfactory',
    'Stained',
    'Gerbil',
    'Busty',
    'Indiana',
    'Maestro',
    'Mama',
    'Papa',
    'Madame',
    'Monsieur',
    'Dickfore',
    'Shawanna',
    'Zap',
    'Zip',
    'Zorro',
    'Spidercum',
    'Cumon',
    'Pasty',
    'Snatch',
    'Beaver',
    'Skittles',
    'Titslap',
    'Putafingerin',
    'Scaly',
    'Cleopatra',
    'Slutty',
    'Slippery',
    'Constable',
    'Tasteless',
    'Haughty',
    'Shaggy',
    'Juggernaut',
    'Nickelback',
    'Vanilla-Flavored',
    'Frothy',
    'Barnyard',
    'Spilt',
    'Woodland',
    'Diarrhea',
    'Lather',
    'Rapture',
    'Leafy',
    'Salty',
    'Flappy',
    'Shafty',
    'Toots',
    'Burnt',
    'Pimply',
    'Milky',
    'Periodstain',
    'Underage',
    'Herpe',
    'Fu Man',
    'Slappa De',
    'Bendacock',
    'Tallywacker',
    'French',
    'Soggy',
    'Hussein',
    'Intimate',
    'Timid',
    'Reluctant',
    'Spurious',
    'Illigitimate',
    'Taco',
    'Pancho',
    'Mayor',
    'Detective',
    'Gumshoe',
    'Officer',
    'Trooper',
    'Stinky',
    'Painful',
    'Windy',
    'Moustache',
    'Handy',
    'Porcelain',
    'Serf',
    'Lord',
    'Lipsync',
    'Chalky',
    'Thirsty',
    'Bejeweled',
    'Moby Dick',
    'Luscious',
    'Decadent',
    'Salacious',
    'Butt Onion'
  ],

  "lasts": [
    'Junkberg',
    'Oppenheimer',
    'Toucherson',
    'Kinkton',
    'Von Bumington',
    'Craghammer',
    'McSplooge',
    'Splatt',
    'McAnus',
    'Scuttlebutt',
    'Wrektum',
    'Jenkums',
    'Pooter',
    'WinkleBottom',
    'the Scrote Whisperer',
    'De Harri',
    'Van Wrinkle',
    'Sugartit',
    'Spanxe',
    'Fasthands',
    'Picklefart',
    'Bikerider',
    'Tittytwister',
    'Dick',
    'Littleween',
    'Fondlesson',
    'Balzac',
    'Lustbottom',
    'Saggybottom',
    'the Yearn',
    'the Racist',
    'Shamebottom',
    'Derkunt',
    'Wriggledick',
    'Thunderschlong',
    'Rabblecock',
    'the Linty Shrew',
    'Slenderdick',
    'the Supple',
    'the Sharter',
    'Snuggleporn',
    'the Ulcer',
    'McTickle',
    'Pajamapants',
    'Pornstache',
    'the Cleveland Steamer',
    'D. Jizzler',
    'Scratch\'n\'Sniff',
    'Soup',
    'Ironcock',
    'Roundbottom',
    'Creampie',
    'BangerDeGang',
    'Jugs',
    'Sphincterine',
    'Analgland',
    'Pitstain',
    'Titpopper',
    'Squash',
    'Heartthrob',
    'Bentdick',
    'Cheesefart',
    'Renalfailure',
    'Grasstain',
    'Titsipper',
    'Vag',
    'Hotdogs',
    'Splooge',
    'Tootsietitz',
    'Sourpussy',
    'the Midget',
    'Maballz',
    'Grundle',
    'Slippers',
    'Cumdumpster',
    'the Sex Act',
    'Skunkfucker',
    'the Furrowed Brow',
    'Fudgepacker',
    'Titfart',
    'Nipslip',
    'Buttface',
    'the Picklefucker',
    'Tasteless',
    'Creamsipper',
    'Creamsicle',
    'Oneball',
    'Threeballs',
    'the Korean Minister',
    'Longbottoms',
    'Longshanks',
    'Tittyspit',
    'Hispanic',
    'Tenderteets',
    'Rinse N\' Repeat',
    'Raptordick',
    'Cumcramps',
    'S\'mores',
    'Sandworm',
    'Sandysnatch',
    'the Gender Bender',
    'Spacecum',
    'Titjuicer',
    'Pubelick Library',
    'Bloodundies',
    'Discharge',
    'Bukkake',
    'Thunderpump',
    'Von Cripplenips',
    'Lutheran Jizzzz',
    'Brokenhip',
    'Egg',
    'Sandwich',
    'the Wedding Singer',
    'Horsecock',
    'Fisted',
    'Sinkhole',
    'Jerkoff',
    'Clamjob',
    'Handjob',
    'Emissions',
    'A\'Plenty',
    'Fingernail',
    'Cumberbund',
    'Purple Nurple',
    'Wrangler',
    'Spanglish',
    'Pecker'
  ],

  "suffixes": [
    'Esq.',
    'M.D.',
    'PhD',
    'STD',
    'PMP',
    'Sr.',
    'Jr.',
    'II',
    'III',
    'IV'
  ]
};

function GetNames(count) {
  var names = [];

  for(var i = 0; i < count; i++) {
    while(true) {
      var name = GetName();
      if(ValidateName(name, names)) {
        names[i] = name;
        break;
      }
    }
  }

  return names;
}

function GetName() {
  var time = new Date().getTime();
  return {
    first: getFirstName(time),
    last: getLastName(time),
    suffix: getSuffix(time)
  };
}

function getFirstName(seed) {
  return names.firsts[Math.floor((Math.random() * seed) % names.firsts.length)];
}

function getLastName(seed) {
  return names.lasts[Math.floor((Math.random() * seed) % names.lasts.length)];
}

function getSuffix(seed) {
  if(Math.floor((Math.random() * seed) % 31) === 0) {
    return names.suffixes[Math.floor((Math.random() * seed) % names.suffixes.length)];
  }

  return null;
}

function ValidateName(name, names) {
  for(var i = 0; i < names.length; i++) {
    if(names[i].first == name.first &&
      names[i].last == name.last) return false;
  }

  return true;
}
